//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IssueManagment.Specs.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("issues-managment-test")]
        public string IssuesManagment_GITHUBUSERNAME {
            get {
                return ((string)(this["IssuesManagment_GITHUBUSERNAME"]));
            }
            set {
                this["IssuesManagment_GITHUBUSERNAME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Issues-Managment-Org")]
        public string IssuesManagment_GITHUBORGANIZATION {
            get {
                return ((string)(this["IssuesManagment_GITHUBORGANIZATION"]));
            }
            set {
                this["IssuesManagment_GITHUBORGANIZATION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string IssuesManagment_OAUTHTOKEN {
            get {
                return ((string)(this["IssuesManagment_OAUTHTOKEN"]));
            }
            set {
                this["IssuesManagment_OAUTHTOKEN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2345jhon")]
        public string IssuesManagment_GITHUBPASSWORD {
            get {
                return ((string)(this["IssuesManagment_GITHUBPASSWORD"]));
            }
            set {
                this["IssuesManagment_GITHUBPASSWORD"] = value;
            }
        }
    }
}
